[tox]
envlist = pep8,py27,py3

[testenv]
deps =
    mock
    pytest
    py3: coverage
commands = pytest tests/

[testenv:py3]
# for py3 env we will get code coverage
commands =
    coverage run --branch --source=buildozer -m pytest {posargs:tests/}
    coverage report -m

[testenv:pep8]
deps = flake8
commands = flake8 buildozer/ tests/

[flake8]
ignore =
    E121, # continuation line under-indented for hanging indent
    E122, # continuation line missing indentation or outdented
    E123, # closing bracket does not match indentation of opening bracket's line
    E125, # continuation line with same indent as next logical line
    E126, # continuation line over-indented for hanging indent
    E127, # continuation line over-indented for visual indent
    E128, # continuation line under-indented for visual indent
    E129, # visually indented line with same indent as next logical line
    E131, # continuation line unaligned for hanging indent
    E226, # missing whitespace around arithmetic operator
    E231, # missing whitespace after ','
    E241, # multiple spaces after ','
    E262, # inline comment should start with '# '
    E265, # block comment should start with '# '
    E301, # expected 1 blank line, found 0
    E302, # expected 2 blank lines, found 1
    E303, # too many blank lines
    E305, # expected 2 blank lines after class or function definition, found 1
    E402, # module level import not at top of file
    E501, # line too long
    E502, # the backslash is redundant between brackets
    E722, # do not use bare 'except'
    E731, # do not assign a lambda expression, use a def
    E741, # ambiguous variable name
    F401, # imported but unused
    F821, # undefined name
    F841, # local variable is assigned to but never used
    W391, # blank line at end of file
    W503, # line break before binary operator
    W504, # line break after binary operator
    W605  # invalid escape sequence
